pipeline {
    agent any 
    
    stages {
        stage('Build') {
            steps {
                sh 'mvn -Denforcer.skip=true clean install'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -Denforcer.skip=true clean'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}

